name: Angular App CI/CD

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Use Node.js version
      uses: actions/setup-node@v1
      with:
        node-version: 16.x

    - name: Install Dependencies
      run: npm install --force

    - name: Replace secret
      uses: cschleiden/replace-tokens@v1
      with:
        tokenPrefix: '{'
        tokenSuffix: '}'
        files: 'src/environments/environment.prod.ts'
      env:
        SECRET_API_KEY: ${{ secrets.API_KEY}}

    - name: Build
      run: npm run build --prod

    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.TOKEN }}
        publish_dir: dist/webapp
        cname: velsuniversitytrolls.in
        commit_message: "Deploy site to GitHub Pages"
